### ISSUE TITLE
🐛 [Bug Report] Multispawn

### ISSUE THREAD

**Issue by ClassicW** [cmangos/issues#2396]
## 🐛 Bugreport

Any npc that needs to be spawned can be spawned endlessly      

![image](https://user-images.githubusercontent.com/71378304/107682442-a2fd2b80-6ca0-11eb-875d-92c8484bc4cd.png)    
 
### Expected behavior                      

It is necessary that when an npc is invoked, we cannot be re-invoked as long as it is present        

### Version & Environment                   

Client Version: "1.12.1" (CLASSIC)                       

CMaNGOS Repo & Commit Hash:a83886f84d16199c9d08d7076e74e256824b5025                              

### Steps to reproduce                           

1. create hero                 
2. go zonexy 77.8 91.3 16           
3. use item ID=10444 twice           
4. see...                  

### Crashlog       

- None

**Comment by insunaa** [comment]
I think the quest needs to be redone in general. Normally what's supposed to happen is that he flies in with his aircraft, then stay there for a minute or so and then fly away again. He isn't supposed to spawn instantly anyway, not to mention multiple times.

Currently this item basically does this: 
```
MariaDB [tbcmangos]> select * from dbscripts_on_event where id=3084\G
*************************** 1. row ***************************
           id: 3084
        delay: 0
     priority: 0
      command: 10
     datalong: 8392
    datalong2: 9000000
    datalong3: 0
  buddy_entry: 0
search_radius: 0
   data_flags: 0
      dataint: 0
     dataint2: 0
     dataint3: 0
     dataint4: 0
            x: 2249
            y: -7221.97
            z: 13.82
            o: 1.02
 condition_id: 0
     comments:
1 row in set (0.001 sec)
```
and nothing more. I mean it works for the quest, but I don't think that's how it should be.
