### ISSUE TITLE
🐛 [Bug Report] Sethekk Halls Heroic Thunderclap roots instead of slows

### ISSUE THREAD

**Issue by insunaa** [cmangos/issues#2419]
## 🐛 Bugreport

Right now the thunderclap (33967) of the Sethekk Guards (18323) roots the player instead of slowing them.
I checked the spell_template and everything seems to be correct as far as I can tell.

Edit: To clarify: With "root" I mean it slows more or equal to 100% movement speed, not that an actual root spell is cast.

### Expected behavior

The Thunderclap spell should slow you down by 40% (SpellEffect2), not root you.

### Version & Environment

Client Version: "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: https://github.com/cmangos/mangos-tbc/tree/84afa33a897f0d9f75635e2a97cd727169980c00

Database Repo & Commit Hash: https://github.com/cmangos/tbc-db/tree/5eec246f43e507a7ca0b03818705dff190d4fcf1

Operating System: 

### Steps to reproduce
1. Create Level 70 character
2. Set Instance difficulty to heroic 
3. `.additem 30633`
4. Enter Sethekk Halls
5. `.mod stam 10000000`
6. `.die` everything that is not a Sethekk Guard
7. ...
8. Profit

## Edit:
OK it looks like the culprit is this: `EffectRealPointsPerLevel2: -0.5` if set to 0 slow *feels* like it has the correct value. Not sure if the  value is accurate to the original, tho.

The spell_template row looks like this:
```
*************************** 1. row ***************************
                           Id: 33967
                     Category: 22
                       CastUI: 0
                       Dispel: 1
                     Mechanic: 11
                   Attributes: 589824
                 AttributesEx: 136
                AttributesEx2: 0
                AttributesEx3: 0
                AttributesEx4: 0
                AttributesEx5: 32768
                AttributesEx6: 0
                      Stances: 0
                   StancesNot: 0
                      Targets: 0
           TargetCreatureType: 0
           RequiresSpellFocus: 0
            FacingCasterFlags: 0
              CasterAuraState: 0
              TargetAuraState: 0
           CasterAuraStateNot: 0
           TargetAuraStateNot: 0
             CastingTimeIndex: 1
                 RecoveryTime: 0
         CategoryRecoveryTime: 0
               InterruptFlags: 15
           AuraInterruptFlags: 0
        ChannelInterruptFlags: 0
                    ProcFlags: 0
                   ProcChance: 101
                  ProcCharges: 0
                     MaxLevel: 0
                    BaseLevel: 20
                   SpellLevel: 20
                DurationIndex: 1
                    PowerType: 0
                     ManaCost: 0
             ManaCostPerlevel: 0
                ManaPerSecond: 0
        ManaPerSecondPerLevel: 0
                   RangeIndex: 1
                        Speed: 0
               ModalNextSpell: 0
                  StackAmount: 0
                       Totem1: 0
                       Totem2: 0
                     Reagent1: 0
                     Reagent2: 0
                     Reagent3: 0
                     Reagent4: 0
                     Reagent5: 0
                     Reagent6: 0
                     Reagent7: 0
                     Reagent8: 0
                ReagentCount1: 0
                ReagentCount2: 0
                ReagentCount3: 0
                ReagentCount4: 0
                ReagentCount5: 0
                ReagentCount6: 0
                ReagentCount7: 0
                ReagentCount8: 0
            EquippedItemClass: -1
     EquippedItemSubClassMask: 0
EquippedItemInventoryTypeMask: 0
                      Effect1: 2
                      Effect2: 6
                      Effect3: 6
              EffectDieSides1: 9
              EffectDieSides2: 1
              EffectDieSides3: 1
              EffectBaseDice1: 1
              EffectBaseDice2: 1
              EffectBaseDice3: 1
          EffectDicePerLevel1: 0
          EffectDicePerLevel2: 0
          EffectDicePerLevel3: 0
    EffectRealPointsPerLevel1: 0
    EffectRealPointsPerLevel2: -0.5
    EffectRealPointsPerLevel3: 0
            EffectBasePoints1: 70
            EffectBasePoints2: -41
            EffectBasePoints3: -34
              EffectMechanic1: 0
              EffectMechanic2: 11
              EffectMechanic3: 0
       EffectImplicitTargetA1: 22
       EffectImplicitTargetA2: 22
       EffectImplicitTargetA3: 22
       EffectImplicitTargetB1: 15
       EffectImplicitTargetB2: 15
       EffectImplicitTargetB3: 15
           EffectRadiusIndex1: 13
           EffectRadiusIndex2: 13
           EffectRadiusIndex3: 13
         EffectApplyAuraName1: 0
         EffectApplyAuraName2: 33
         EffectApplyAuraName3: 138
             EffectAmplitude1: 0
             EffectAmplitude2: 0
             EffectAmplitude3: 0
         EffectMultipleValue1: 0
         EffectMultipleValue2: 0
         EffectMultipleValue3: 0
           EffectChainTarget1: 0
           EffectChainTarget2: 0
           EffectChainTarget3: 0
              EffectItemType1: 0
              EffectItemType2: 0
              EffectItemType3: 0
             EffectMiscValue1: 0
             EffectMiscValue2: 0
             EffectMiscValue3: 0
            EffectMiscValueB1: 0
            EffectMiscValueB2: 0
            EffectMiscValueB3: 0
          EffectTriggerSpell1: 0
          EffectTriggerSpell2: 0
          EffectTriggerSpell3: 0
   EffectPointsPerComboPoint1: 0
   EffectPointsPerComboPoint2: 0
   EffectPointsPerComboPoint3: 0
                  SpellVisual: 145
                  SpellIconID: 199
                 ActiveIconID: 0
                SpellPriority: 0
                    SpellName: Thunderclap
                   SpellName2:
                   SpellName3:
                   SpellName4:
                   SpellName5:
                   SpellName6:
                   SpellName7:
                   SpellName8:
                   SpellName9:
                  SpellName10:
                  SpellName11:
                  SpellName12:
                  SpellName13:
                  SpellName14:
                  SpellName15:
                  SpellName16:
                        Rank1:
                        Rank2:
                        Rank3:
                        Rank4:
                        Rank5:
                        Rank6:
                        Rank7:
                        Rank8:
                        Rank9:
                       Rank10:
                       Rank11:
                       Rank12:
                       Rank13:
                       Rank14:
                       Rank15:
                       Rank16:
           ManaCostPercentage: 0
        StartRecoveryCategory: 133
            StartRecoveryTime: 1500
               MaxTargetLevel: 0
              SpellFamilyName: 0
             SpellFamilyFlags: 0
           MaxAffectedTargets: 0
                     DmgClass: 1
               PreventionType: 1
               StanceBarOrder: 0
               DmgMultiplier1: 1
               DmgMultiplier2: 1
               DmgMultiplier3: 1
                 MinFactionId: 0
                MinReputation: 0
           RequiredAuraVision: 0
               TotemCategory1: 0
               TotemCategory2: 0
                       AreaId: 0
                   SchoolMask: 8
                 IsServerSide: 0
         AttributesServerside: 0
```
